{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "App Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"flask-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(flask_requests_total[1m])", "legendFormat": "__auto" },
    {
     "expr": "rate(flask_request_latency_seconds_sum[1m])\n/\nrate(flask_request_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  rate(flask_request_latency_seconds_bucket[5m])\n)\n\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}